# Generated by Django 3.2.5 on 2021-07-12 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=20)),
                ('pprice', models.IntegerField(default='0')),
                ('description', models.CharField(max_length=50)),
            ],
        ),
    ]
